### ISSUE TITLE
about the parser --linear_eval=True

### ISSUE THREAD

**Issue by luochengbin823** [akhilmathurs/orchestra#4]
when i excute python main.py --config_dict="{'train_mode': 'orchestra', 'da_method': 'orchestra', 'local_lr': 0.003}" --linear_eval=True.

It will be prompt “main.py: error: unrecognized arguments: --linear_eval=True”.  What does --linear_eval=True do?How should i solve this problem？

**Comment by EkdeepSLubana** [comment]
Hi! Sorry about this; there was a typo. It should have been `do_linear=True` instead of `linear_eval=True` in the script. I've fixed it now. Feel free to post here if still doesn't work.

The argument tells the script to, after training the model, run the linear eval protocol popularly used in SSL for evaluation.
